# constants.py
DISPLAY_PIXEL_HEIGHT = 400
DISPLAY_PIXEL_WIDTH = 640
MAX_LINE_LENGTH = 26
LINE_HEIGHT = 50
STATUS_LINE_HEIGHT = LINE_HEIGHT
HORIZONTAL_LINE_Y = DISPLAY_PIXEL_HEIGHT - (STATUS_LINE_HEIGHT * 2)
MAX_LINES = (DISPLAY_PIXEL_HEIGHT - STATUS_LINE_HEIGHT * 2) // LINE_HEIGHT
